defaults:
  - hydra: default
  - paths: default
  - dataset: cylinder_toy_field
  - manifold: cylindrical
  - logging: default
  - model: c_unet
  - training: default
  - evaluate: default
  - _self_
