defaults:
  - hydra: default
  - paths: default
  - dataset: skm_tea
  - logging: w_and_b
  - model: c_unet_attention
  - training: default
  - generate: default
  - evaluate: default
  - reconstruct: default
  - _self_
