defaults:
  - hydra: default
  - paths: default
  - dataset: fastmri_local
  - manifold: cylindrical
  - logging: default
  - model: c_unet_attention
  - training: default
  - evaluate: default
  - _self_
